language: node_js
node_js:
  - node
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: TqXlbXHndq58yLtX+UsgMPtpmZt7oqGv9p61aWV7U2ViNXspT4PXJI9OoMRv4dTOfQGULkg5XXJ+GfzNXRX4Ck7s8I/2WxP27lkIAmmk35gzp03Ma7EwTOfvxZArD6kxg3p33XbI6Pk8hhUTajsOelVF8JyDm9P3zPjItzqOb91jsp7Kq81BFpE+UdL/OaI5B4tPSos49l0MpoMF+/RrqCmUakmhPpNcKww8UI0uUPVMu59e+1avuqpRsYMdkPvPz0xc9AwZDd/Rdq8funoGTdLo5pi4ICVN/+n2dC0FaN/ykM3yGUCntAvoJMheLfVSGkHfn8CJyweWA560j3im/z6h5GzMHkLonMP3H2bgvcc42ubyWFLJp26gMu5ae0xQ+Pw23tfmTb2F/pO6Du0JvaGXtTRYQ/hdGglTLGbbrTA68gdQ4/+ROEgdJ/tDX0BGgO4qtTfxza6kXcbqVpHUgWR8C+wMbrmKVZ33U9gLZFS0k2nwHIVw7YNqKOX2Ws2NnLjCUYlPfJlNOL0vwWyG4qj//GVzDeH4unqMVwi+QvmAAqIyqqPHEk4Q2yKGo7lHqapK4A6YK9SvTK1CNzkL6VgQ3PTbqmQuqu3nJBjf4NO1q1eXEz27JK8mbAqnayRR0NrRx69k5fgZpOScKRDL2WojqZhC1jVKAWDmNmCjqu0=
  app: colorsbypicasso
