language: node_js
node_js:
  - 7
  - 8
  - 10
  before_install:
  - npm install -g npm
  script:
  - npm install
  - npm run pretest
  deploy:
    provider: heroku
    api_key:
      secure: <3421432>
    app: automate-heroku
    on:
      repo: edwindelbosque/colorsbypicasso